package com.features.test_app_githubusersearch.api.models

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonPropertyOrder

@JsonPropertyOrder(
    "id", "node_id", "name", "full_name", "private", "owner", "html_url", "description", "fork", "url",
    "forks_url", "keys_url", "collaborators_url", "teams_url", "hooks_url", "issue_events_url", "events_url",
    "assignees_url", "branches_url", "tags_url", "blobs_url", "git_tags_url", "git_refs_url", "trees_url",
    "statuses_url", "languages_url", "stargazers_url", "contributors_url", "subscribers_url", "subscription_url",
    "commits_url", "git_commits_url", "comments_url", "issue_comment_url", "contents_url", "compare_url", "merges_url",
    "archive_url", "downloads_url", "issues_url", "pulls_url", "milestones_url", "notifications_url", "labels_url",
    "releases_url", "deployments_url", "created_at", "updated_at", "pushed_at", "git_url", "ssh_url", "clone_url",
    "svn_url", "homepage", "size", "stargazers_count", "watchers_count", "language", "has_issues", "has_projects",
    "has_downloads", "has_wiki", "has_pages", "forks_count", "mirror_url", "archived", "disabled", "open_issues_count",
    "license", "forks", "open_issues", "watchers", "default_branch"
    )
class RepoModel (
    @JsonProperty("forks_count") val forks_count: Int,
    @JsonProperty("stargazers_count") val stargazers_count: Int,
    @JsonProperty("name") val name: String,
    @JsonProperty("url") val url: String,
    @JsonProperty("id") val id: Any?,
    @JsonProperty("node_id") val node_id: Any?,
    @JsonProperty("full_name") val full_name: Any?,
    @JsonProperty("private") val privates: Any?,
    @JsonProperty("owner") val owner: Any?,
    @JsonProperty("html_url") val html_url: Any?,
    @JsonProperty("description") val description: Any?,
    @JsonProperty("fork") val fork: Any?,
    @JsonProperty("forks_url") val forks_url: Any?,
    @JsonProperty("keys_url") val keys_url: Any?,
    @JsonProperty("collaborators_url") val collaborators_url: Any?,
    @JsonProperty("teams_url") val teams_url: Any?,
    @JsonProperty("hooks_url") val hooks_url: Any?,
    @JsonProperty("issue_events_url") val issue_events_url: Any?,
    @JsonProperty("events_url") val events_url: Any?,
    @JsonProperty("assignees_url") val assignees_url: Any?,
    @JsonProperty("branches_url") val branches_url: Any?,
    @JsonProperty("tags_url") val tags_url: Any?,
    @JsonProperty("blobs_url") val blobs_url: Any?,
    @JsonProperty("git_tags_url") val git_tags_url: Any?,
    @JsonProperty("git_refs_url") val git_refs_url: Any?,
    @JsonProperty("trees_url") val trees_url: Any?,
    @JsonProperty("statuses_url") val statuses_url: Any?,
    @JsonProperty("languages_url") val languages_url: Any?,
    @JsonProperty("stargazers_url") val stargazers_url: Any?,
    @JsonProperty("contributors_url") val contributors_url: Any?,
    @JsonProperty("subscribers_url") val subscribers_url: Any?,
    @JsonProperty("subscription_url") val subscription_url: Any?,
    @JsonProperty("commits_url") val commits_url: Any?,
    @JsonProperty("git_commits_url") val git_commits_url: Any?,
    @JsonProperty("comments_url") val comments_url: Any?,
    @JsonProperty("issue_comment_url") val issue_comment_url: Any?,
    @JsonProperty("contents_url") val contents_url: Any?,
    @JsonProperty("compare_url") val compare_url: Any?,
    @JsonProperty("merges_url") val merges_url: Any?,
    @JsonProperty("archive_url") val archive_url: Any?,
    @JsonProperty("downloads_url") val downloads_url: Any?,
    @JsonProperty("issues_url") val issues_url: Any?,
    @JsonProperty("pulls_url") val pulls_url: Any?,
    @JsonProperty("milestones_url") val milestones_url: Any?,
    @JsonProperty("notifications_url") val notifications_url: Any?,
    @JsonProperty("labels_url") val labels_url: Any?,
    @JsonProperty("releases_url") val releases_url: Any?,
    @JsonProperty("deployments_url") val deployments_url: Any?,
    @JsonProperty("created_at") val created_at: Any?,
    @JsonProperty("updated_at") val updated_at: Any?,
    @JsonProperty("pushed_at") val pushed_at: Any?,
    @JsonProperty("git_url") val git_url: Any?,
    @JsonProperty("ssh_url") val ssh_url: Any?,
    @JsonProperty("clone_url") val clone_url: Any?,
    @JsonProperty("svn_url") val svn_url: Any?,
    @JsonProperty("homepage") val homepage: Any?,
    @JsonProperty("size") val size: Any?,
    @JsonProperty("watchers_count") val watchers_count: Any?,
    @JsonProperty("language") val language: Any?,
    @JsonProperty("has_issues") val has_issues: Any?,
    @JsonProperty("has_projects") val has_projects: Any?,
    @JsonProperty("has_downloads") val has_downloads: Any?,
    @JsonProperty("has_wiki") val has_wiki: Any?,
    @JsonProperty("has_pages") val has_pages: Any?,
    @JsonProperty("mirror_url") val mirror_url: Any?,
    @JsonProperty("archived") val archived: Any?,
    @JsonProperty("disabled") val disabled: Any?,
    @JsonProperty("open_issues_count") val open_issues_count: Any?,
    @JsonProperty("logilicensen") val license: Any?,
    @JsonProperty("forks") val forks: Any?,
    @JsonProperty("open_issues") val open_issues: Any?,
    @JsonProperty("watchers") val watchers: Any?,
    @JsonProperty("default_branch") val default_branch: Any?
)
